name: ci-cd laba3

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_IMAGE: yulk0n/trr_lab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd ./src && make build
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: laba3
        path: ./src/laba3

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: download binary
      uses: actions/download-artifact@v4
      with:
        name: laba3
        path: ./src
    - name: Run tests
      run: cd ./src && make test

  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build, test]
    steps:
    - uses: actions/checkout@v4
    - name: deb package build
      run: |
        mkdir -p deb_pac3/DEBIAN
        echo "Package: laba3" > deb_pac3/DEBIAN/control
        echo "Version: 3.0" >> deb_pac3/DEBIAN/control
        echo "Section: utils" >> deb_pac3/DEBIAN/control
        echo "Architecture: amd64" >> deb_pac3/DEBIAN/control
        echo "Maintainer: Yulia and Denis" >> deb_pac3/DEBIAN/control
        echo "Depends: g++, libc6, libstdc++6, gcc-8-base | libgcc-s1, build-essential, libstdc++-dev" >> deb_pac3/DEBIAN/control
        echo "Description: Factorial calculator" >> deb_pac3/DEBIAN/control

        cd ./src && make
        cd ..
        dpkg-deb --build deb_pac3 laba3_pkg.deb
        dpkg -c laba3_pkg.deb
    - name: upload deb package
      uses: actions/upload-artifact@v4
      with:
        name: laba3-deb
        path: laba3_pkg.deb

  deploy:
    runs-on: ubuntu-latest
    needs: package
    services:
      docker:
        image: docker:dind
        options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: download deb package
      uses: actions/download-artifact@v4
      with:
        name: laba3-deb
        path: .
    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:latest
    - name: verify container
      run: |
        echo "5" | docker run -i --rm ${{ env.DOCKER_IMAGE }}:latest
        docker ps -a
