name: ci-cd laba3

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd ./src && make build
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: laba3
        path: ./src/laba3

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: download binary
      uses: actions/download-artifact@v4
      with:
        name: laba3
        path: ./src
    - name: Run tests
      run: cd ./src && make test

  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build, test]
    steps:
    - uses: actions/checkout@v4
    - name: deb package build
      run: |
        mkdir -p deb_pac3/DEBIAN
        echo "Package: laba3" > deb_pac3/DEBIAN/control
        echo "Version: 3.0" >> deb_pac3/DEBIAN/control
        echo "Section: utils" >> deb_pac3/DEBIAN/control
        echo "Architecture: amd64" >> deb_pac3/DEBIAN/control
        echo "Maintainer: Yulia and Denis" >> deb_pac3/DEBIAN/control
        echo "Depends: g++, libc6, libstdc++6, gcc-8-base | libgcc-s1, build-essential, libstdc++-dev" >> deb_pac3/DEBIAN/control
        echo "Description: Factorial calculator" >> deb_pac3/DEBIAN/control

        cd ./src && make
        cd ..
        dpkg-deb --build deb_pac3 laba3_pkg.deb
        dpkg -c laba3_pkg.deb
        
    #- name: create-release
     # uses: ncipollo/release-action@v1.14.0
      #with:
       # artifactErrorsFailBuild: true 
        #artifact: laba2_pkg.deb  
        #body: Factorial 
        #name: laba2 
        #tag: laba2-release
        #token: ${{ secrets.MY_SECRET_NAME }}
