name: ci-cd laba2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: cd ./src && make build
    - name: upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: laba2
        path: ./src/laba2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: download binary
      uses: actions/download-artifact@v4
      with:
        name: laba2
        path: ./src
    - name: Run tests
      run: cd ./src && make test

  package:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v4
    - name: download binary
      uses: actions/download-artifact@v4
      with:
        name: laba2
        path: ./src
    - name: deb package build
      run: |
        mkdir -p deb_pac2/DEBIAN
        echo "Package: laba2 >> deb_pac2/DEBIAN/control
        echo "Version: 2.0" >> deb_pac2/DEBIAN/control
        echo "Section: utils" >> deb_pac2/DEBIAN/control
        echo "Architecture: amd64" >> deb_pac2/DEBIAN/control
        echo "Maintainer: Yulia and Denis>> deb_pac2/DEBIAN/control
        echo "Depends: g++, libc6, libstdc++6, gcc-8-base | libgcc-s1, build-essential, libstdc++-dev" >> deb_pac2/DEBIAN/control
        echo "Description: Factorial calculator" >> deb_pac2/DEBIAN/control

        mkdir -p deb_pac2/usr/bin
        cp ./src/laba2 deb_pac2/usr/bin/
        
        dpkg-deb --build deb_pac2 laba2_pkg.deb
