name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4  # Клонирует репозиторий (корень = $GITHUB_WORKSPACE)
  
    - name: Create ./usr/bin
      run: |
        mkdir -p ./usr/bin
        ls -l ./usr/bin 
        ls -l ./ # Проверка
